name: build
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build-gl-linux:
    name: Build vpxds-linux-x64
    env:
      CC: gcc-12
      CXX: g++-12
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev libsdl2-image-dev
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build
          cmake --build build
      - run: |
          mkdir tmp
          cp build/vpxds tmp
          cp vpxds.ini tmp
      - uses: actions/upload-artifact@v3
        with:
          name: vpxds-linux-x64
          path: tmp
